//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inspinia_MVC5_SeedProject.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Date.
        /// </summary>
        public static string ActivationDateColHeader {
            get {
                return ResourceManager.GetString("ActivationDateColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Instagram Profile.
        /// </summary>
        public static string CreateHeaderInstProf {
            get {
                return ResourceManager.GetString("CreateHeaderInstProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ip Address.
        /// </summary>
        public static string CreateHeaderIpAddr {
            get {
                return ResourceManager.GetString("CreateHeaderIpAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ip Range.
        /// </summary>
        public static string CreateHeaderIpRange {
            get {
                return ResourceManager.GetString("CreateHeaderIpRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Twitter Profile.
        /// </summary>
        public static string CreateHeaderTwitProf {
            get {
                return ResourceManager.GetString("CreateHeaderTwitProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation to Delete Instagram Profile.
        /// </summary>
        public static string DeleteHeaderInstProf {
            get {
                return ResourceManager.GetString("DeleteHeaderInstProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation to Delete Ip Address.
        /// </summary>
        public static string DeleteHeaderIpAddr {
            get {
                return ResourceManager.GetString("DeleteHeaderIpAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation to Delete Ip Range.
        /// </summary>
        public static string DeleteHeaderIpRange {
            get {
                return ResourceManager.GetString("DeleteHeaderIpRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation to Delete Twitter Profile.
        /// </summary>
        public static string DeleteHeaderTwitProf {
            get {
                return ResourceManager.GetString("DeleteHeaderTwitProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Instagram Profile.
        /// </summary>
        public static string EditHeaderInstProf {
            get {
                return ResourceManager.GetString("EditHeaderInstProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Ip Address.
        /// </summary>
        public static string EditHeaderIpAddr {
            get {
                return ResourceManager.GetString("EditHeaderIpAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Ip Range.
        /// </summary>
        public static string EditHeaderIpRange {
            get {
                return ResourceManager.GetString("EditHeaderIpRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Twitter Profile.
        /// </summary>
        public static string EditHeaderTwitProf {
            get {
                return ResourceManager.GetString("EditHeaderTwitProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string EntityBaseTitle {
            get {
                return ResourceManager.GetString("EntityBaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Profiles.
        /// </summary>
        public static string IndexHeaderInstProf {
            get {
                return ResourceManager.GetString("IndexHeaderInstProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Addresses.
        /// </summary>
        public static string IndexHeaderIpAddr {
            get {
                return ResourceManager.GetString("IndexHeaderIpAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Ranges.
        /// </summary>
        public static string IndexHeaderIpRange {
            get {
                return ResourceManager.GetString("IndexHeaderIpRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Profiles.
        /// </summary>
        public static string IndexHeaderTwitProf {
            get {
                return ResourceManager.GetString("IndexHeaderTwitProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string IndexTablePropAction {
            get {
                return ResourceManager.GetString("IndexTablePropAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string IndexTablePropCreateNew {
            get {
                return ResourceManager.GetString("IndexTablePropCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Profile.
        /// </summary>
        public static string InstagramProfile {
            get {
                return ResourceManager.GetString("InstagramProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid ip address (ex. 123.32.45.56).
        /// </summary>
        public static string IpLengthCheck {
            get {
                return ResourceManager.GetString("IpLengthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Range.
        /// </summary>
        public static string IpRange {
            get {
                return ResourceManager.GetString("IpRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid ip range (i.e. between 0-32).
        /// </summary>
        public static string IpRangeLengthCheck {
            get {
                return ResourceManager.GetString("IpRangeLengthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip range is required.
        /// </summary>
        public static string IpRangeRequired {
            get {
                return ResourceManager.GetString("IpRangeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address is required.
        /// </summary>
        public static string IpRequired {
            get {
                return ResourceManager.GetString("IpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string ModuleColumnHeader {
            get {
                return ResourceManager.GetString("ModuleColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service and systems availability checker module.
        /// </summary>
        public static string ModuleName1 {
            get {
                return ResourceManager.GetString("ModuleName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter activity checker module.
        /// </summary>
        public static string ModuleName2 {
            get {
                return ResourceManager.GetString("ModuleName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram activity checker module.
        /// </summary>
        public static string ModuleName3 {
            get {
                return ResourceManager.GetString("ModuleName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Policy.
        /// </summary>
        public static string PolicyCreateTitle {
            get {
                return ResourceManager.GetString("PolicyCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a schedule period.
        /// </summary>
        public static string PolicyDefineScheduleInfo {
            get {
                return ResourceManager.GetString("PolicyDefineScheduleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation to Delete Policy.
        /// </summary>
        public static string PolicyDeleteTitle {
            get {
                return ResourceManager.GetString("PolicyDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Policy.
        /// </summary>
        public static string PolicyEditTitle {
            get {
                return ResourceManager.GetString("PolicyEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all necessary fields!.
        /// </summary>
        public static string PolicyFillAllFields {
            get {
                return ResourceManager.GetString("PolicyFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string PolicyScheduleDayInfo {
            get {
                return ResourceManager.GetString("PolicyScheduleDayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish at.
        /// </summary>
        public static string PolicyScheduleFinishAt {
            get {
                return ResourceManager.GetString("PolicyScheduleFinishAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string PolicyScheduleHourInfo {
            get {
                return ResourceManager.GetString("PolicyScheduleHourInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string PolicyScheduleMinuteInfo {
            get {
                return ResourceManager.GetString("PolicyScheduleMinuteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string PolicyScheduleMonthInfo {
            get {
                return ResourceManager.GetString("PolicyScheduleMonthInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string PolicySchedulePeriod {
            get {
                return ResourceManager.GetString("PolicySchedulePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at.
        /// </summary>
        public static string PolicyScheduleStartAt {
            get {
                return ResourceManager.GetString("PolicyScheduleStartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string PolicyScheduleWeekInfo {
            get {
                return ResourceManager.GetString("PolicyScheduleWeekInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least an asset.
        /// </summary>
        public static string PolicySelectEntityInfo {
            get {
                return ResourceManager.GetString("PolicySelectEntityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select instagram profile(s) for policy.
        /// </summary>
        public static string PolicySelectInstagramInfo {
            get {
                return ResourceManager.GetString("PolicySelectInstagramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address assets.
        /// </summary>
        public static string PolicySelectIpCol {
            get {
                return ResourceManager.GetString("PolicySelectIpCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ip / ip range for policy.
        /// </summary>
        public static string PolicySelectIpInfo {
            get {
                return ResourceManager.GetString("PolicySelectIpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip range assets.
        /// </summary>
        public static string PolicySelectIpRangeCol {
            get {
                return ResourceManager.GetString("PolicySelectIpRangeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a module for policy.
        /// </summary>
        public static string PolicySelectModuleInfo {
            get {
                return ResourceManager.GetString("PolicySelectModuleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select twitter profile(s) for policy.
        /// </summary>
        public static string PolicySelectTwitterInfo {
            get {
                return ResourceManager.GetString("PolicySelectTwitterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string PolicyStatusActive {
            get {
                return ResourceManager.GetString("PolicyStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string PolicyStatusInactive {
            get {
                return ResourceManager.GetString("PolicyStatusInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Step.
        /// </summary>
        public static string PolicyStep1 {
            get {
                return ResourceManager.GetString("PolicyStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Step.
        /// </summary>
        public static string PolicyStep2 {
            get {
                return ResourceManager.GetString("PolicyStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Step.
        /// </summary>
        public static string PolicyStep3 {
            get {
                return ResourceManager.GetString("PolicyStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow steps....
        /// </summary>
        public static string PolicyStepFollow {
            get {
                return ResourceManager.GetString("PolicyStepFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string PolicyTableTitle {
            get {
                return ResourceManager.GetString("PolicyTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string PolicyTitle {
            get {
                return ResourceManager.GetString("PolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Id.
        /// </summary>
        public static string ProfileId {
            get {
                return ResourceManager.GetString("ProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile id is required.
        /// </summary>
        public static string ProfileIdRequired {
            get {
                return ResourceManager.GetString("ProfileIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once every &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string Schedule1 {
            get {
                return ResourceManager.GetString("Schedule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once  every &lt;b&gt;{0}&lt;/b&gt; between &lt;b&gt;{1}&lt;/b&gt; and &lt;b&gt;{2}&lt;/b&gt; hours.
        /// </summary>
        public static string Schedule1Between {
            get {
                return ResourceManager.GetString("Schedule1Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string ScheduleColumnHeader {
            get {
                return ResourceManager.GetString("ScheduleColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        public static string ScheduleDay {
            get {
                return ResourceManager.GetString("ScheduleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s).
        /// </summary>
        public static string ScheduleHour {
            get {
                return ResourceManager.GetString("ScheduleHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        public static string ScheduleMinute {
            get {
                return ResourceManager.GetString("ScheduleMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        public static string ScheduleMonth {
            get {
                return ResourceManager.GetString("ScheduleMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once every &lt;b&gt;{0} {1}&lt;/b&gt;.
        /// </summary>
        public static string ScheduleMore {
            get {
                return ResourceManager.GetString("ScheduleMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once every &lt;b&gt;{0} {1}&lt;/b&gt; between &lt;b&gt;{2}&lt;/b&gt; and &lt;b&gt;{3}&lt;/b&gt; hours.
        /// </summary>
        public static string ScheduleMoreBetween {
            get {
                return ResourceManager.GetString("ScheduleMoreBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s).
        /// </summary>
        public static string ScheduleWeek {
            get {
                return ResourceManager.GetString("ScheduleWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Language.
        /// </summary>
        public static string SettingsChooseYourLanguage {
            get {
                return ResourceManager.GetString("SettingsChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to Search.
        /// </summary>
        public static string SocNetSearchStr {
            get {
                return ResourceManager.GetString("SocNetSearchStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to search is required.
        /// </summary>
        public static string SocNetSearchStrRequired {
            get {
                return ResourceManager.GetString("SocNetSearchStrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusColHeader {
            get {
                return ResourceManager.GetString("StatusColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Profile.
        /// </summary>
        public static string TwitterProfile {
            get {
                return ResourceManager.GetString("TwitterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateBtn {
            get {
                return ResourceManager.GetString("UpdateBtn", resourceCulture);
            }
        }
    }
}
